# Use a Maven image with Java 24 to build the application
FROM maven:3.9.6-openjdk-24 AS builder
# Set the working directory in the container
WORKDIR /app
# Copy the project files into the container
COPY . .
# Package the application as a layered JAR
RUN mvn clean package -DskipTests

# Use a lightweight JRE base image with Java 24 to run the application
FROM eclipse-temurin:24-jre-alpine
# Set the working directory
WORKDIR /app
# Copy the layers from the build stage
COPY --from=builder /app/target/licensing-service-0.0.1-SNAPSHOT.jar /app.jar
# Expose the application port
EXPOSE 8080
# Define the command to run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]
